### ISSUE TITLE
CloudFront Error When Updating Larger WordPress Plugins / Initiated Cascade of Failing EC2 Instances

### ISSUE THREAD

**Issue by ILLUMINICE** [widdix/aws-cf-templates#93] opened 2017-07-19 02:48 UTC
Hi Michael & Andreas,

I've been having a consistent issue here when attempting to run plugin updates from within the WordPress admin. This problem has been present from the very first day I setup the CF stack. I'm using the WordPress Aurora CF template.

What is happening is that larger plugins are unable to complete their updates, and produce this error directly in the WordPress admin:

Update Failed: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"> ERROR: The request could not be satisfied ERROR The request could not be satisfied. CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection. Generated by cloudfront (CloudFront) Request ID: AHqgd8KK0806Bt6DLtYiDLpKcJR00lq9zaUJnTJumKKY8IouheLxyQ==

In some cases this results in the plugins being corrupted, and at other times they do fully update despite this error being displayed. I've also had a number of instances where the website became completely unavailable for a few minutes and was stuck in maintenance mode (the maintenance mode created by WordPress in the back-end when running plugin updates). Luckily in those instances the website became available again after a few minutes.

There seems to be some kind of time-out occurring here with respect to plugin updates. I am concerned about this since it can result in corrupted plugins, or worse making the entire website unavailable.

I'd welcome your insights into the cause of this...

~ Michael

**Comment by ILLUMINICE** [comment] 2017-07-19 03:20
I need to add that the above error actually started to crash all my EC2 instances, and each time AWS tried to create a new instance, it would crash again. I believe this is due to some of my plugins being corrupted when the update process was interrupted.

I'm in the process right now of removing all of my plugins and uploading fresh versions to ensure there are no corrupted files.

The way this is working right now I cannot trust updating any plugins from within the WordPress admin, and am having to rely on manually updating them.

~ Michael

**Comment by ILLUMINICE** [comment] 2017-07-19 03:54
My EC2 instances are continuing to fail, be deleted, and recreated. Each new instance only remains online a few minutes before failing. This all started after I attempted to update a few plugins from within WordPress as described above, and received the CloudFront related error.

I'm seeing this error in the auto-scaling group each time an instance is deleted:

At 2017-07-19T03:33:56Z an instance was taken out of service in response to a ELB system health check failure.

 I've deactivated all of my plugins, and removed the files, yet the instances continue to fail. I want to upload fresh versions of all the plugins, but the instances don't stay online long enough for me to connect to them. This is quite frustrating...

~ Michael

**Comment by ILLUMINICE** [comment] 2017-07-19 04:58
I'm now unable to work, as my ec2 instances are completely unstable. They simply terminate, recreate, and terminate, over and over again. I have no explanation as to why this is occurring.

~ Michael

**Comment by ILLUMINICE** [comment] 2017-07-19 05:04
Here are some screenshots demonstrating what is going on... the first with the instances being deleted and recreated, and the other screenshot is from the auto-scaling group activity history.

![screenshot2](https://user-images.githubusercontent.com/11562655/28351481-09142f36-6c05-11e7-9809-389f689a1af4.jpg)
![screenshot](https://user-images.githubusercontent.com/11562655/28351482-091549c0-6c05-11e7-9e58-fb8b04881c37.jpg)

**Comment by ILLUMINICE** [comment] 2017-07-19 05:10
To make matters worse, now both my website and WordPress admin are inaccessible... and all this started from simply trying to run plugin updates.

**Comment by michaelwittig** [comment] 2017-07-19 05:11
this might be related: #61

**Comment by ILLUMINICE** [comment] 2017-07-19 05:20
Hi Michael,

I just read #61, and that certainly sounds like the source of the issue updating the plugins. I noticed the pattern that the error seemed to occur only when updating larger plugins. I figured it was a timeout related issue. I agree with the other user that a timeout of 60 seconds makes a lot more sense. There are some larger plugins (like BuddyPress, WordFence, Yoast, etc) which can take about 20-30 seconds to update.

I'm already looking at an alternate workflow for updating plugins manually, instead of through WordPress. I'll be tracking our plugin updates in git, updating them manually, and then pushing that off to the EFS. Doing it that way will avoid potential timeout issues like this, and possibly corrupting plugins.

Putting the update issue aside, I can't explain what occurred here afterwards. My ec2 instances continue to immediately fail, and I cannot access the website or WP admin. I already had a lot of work done in this site, and cannot afford to just start over. This kind of instability honestly has me very concerned about the future of the platform I'm building, and doing this on AWS.

Is there any way to tell what is going on with these instances and why they continue to fail?

~ Michael

**Comment by michaelwittig** [comment] 2017-07-19 05:37
It looks like CloudFormation does still not support setting a custom origin timeout.
One posible workaround is to directly connect to the loadbalancer instead of the cdn. You could switch the CNAME/Aliad record in Route 53 to point to the loadbalancer and perform the updates.

**Comment by michaelwittig** [comment] 2017-07-19 05:38
Can you look into CloudWatch Logs. The instances may report what's wrong there.

**Comment by ILLUMINICE** [comment] 2017-07-19 05:54
Are you saying that when I run plugin updates from within the WordPress admin it is connecting first through the CDN? Shouldn't all activity in the WordPress admin bypass the CDN completely? This would seem to make more sense.

That's frustrating regarding the custom origin timeout setting, and that CF still doesn't support it. I noticed the other user mentioned this was affecting not just plugin uploads, but also other media uploads. This could become a major issue for us since our platform relies upon larger media uploads. I haven't had a chance to test this yet. Are we looking at potential issues when uploading all forms of large media?

I'm looking into my CloudWatch logs right now...

~ Michael

**Comment by ILLUMINICE** [comment] 2017-07-19 06:05
There are so many different logs to look at, it's tough to know which one is best. They all have many updates from today.

I've managed to regain access to my website and WP admin. I think this may have something to do with my earlier changes to the ownership of files. I've been dealing with difficulties around the fact that WordPress requires having file ownership in order to do many normal functions, but that I need file ownership in order to upload, delete, and edit files in the EFS. I initially tried to find a single set of settings that would enable both WordPress to have access, and me to have the access I needed simultaneously. I tried different combinations of ownership for owner and group, but nothing I did would work for both WordPress and me.

Ultimately I decided to give WordPress ownership of what it needed, and myself ownership over things I need to change on a regular basis (like our child theme). However, earlier I did change the ownership for wp-config.php so that I could edit it further, and perhaps this caused the failures. I'm honestly not sure. I changed the ownership back to apache a few minutes ago, and suddenly the website was accessible. Then I changed it back to myself (ec2-user), and the website is still up and accessible.

I'm really not sure what caused the instability with the instances, but in the last few minutes it seems to have stabilized. Do you think it could have been ownership related?

~ Michael

**Comment by ILLUMINICE** [comment] 2017-07-19 06:29
The instances have definitely stabilized now...

I looked in the logs for /var/log/httpd/error_log and noticed a lot of this:

[Wed Jul 19 05:29:20.124218 2017] [:error] [pid 2854] [client 10.32.35.224:6880] PHP Warning: require_once(/var/www/html/wp-config.php): failed to open stream: Permission denied in /var/www/html/wp-load.php on line 37

and

[Wed Jul 19 05:29:20.124230 2017] [:error] [pid 2854] [client 10.32.35.224:6880] PHP Fatal error: require_once(): Failed opening required '/var/www/html/wp-config.php' (include_path='.:/usr/share/pear7:/usr/share/php7') in /var/www/html/wp-load.php on line 37

Obviously there was an issue accessing wp-config.php. Perhaps the failure of my instances, and the original issues I reported updating plugins were unrelated. I was working on many things simultaneously tonight. Before I worked on the plugins I was working on customizing file and folder ownership.

Strangely it seems that having wp-config.php with the ownership ec2-user:ec2-user doesn't always cause problems. I have it set that way right now and the instances are stable. But I believe this was the cause of the problem earlier for some reason. I'm going to change the ownership of it back to apache:apache until I need to make edits to it again. I don't want to risk this kind of instability in the future.

.....

As for the problems updating plugins, please see my earlier posts and the questions I had. I'm worried not only about plugin updates, but uploading media through the website itself. We have a publishing platform we're building, and it will involve some large media uploads. I'm worried about having the same kind of timeout issues we've seen associated with the plugins.

~ Michael

**Comment by ILLUMINICE** [comment] 2017-07-19 08:30
Hi Michael,

I'd greatly appreciate your help with my questions above...

I actually ran into another instance of a timeout associated with the CloudFront distribution, this time with a WordPress import function.

I really need to know if this is going to affect all uploads to the website, as that would interfere with the entire platform.

Your workaround to point the domain in Route 53 to the load balancer directly is a good idea, but really doesn't help for standard functions on the site that require large uploads. I never thought that the CDN would cause problems of this type, with uploads. My understanding was that it was only used for download purposes when viewing static content on the site. But I can see it's interfering with many normal functions.

I'd greatly appreciate your further thoughts on all of this...

~ Michael

**Comment by michaelwittig** [comment] 2017-07-20 07:03
the issue is not a large upload. it's wordpress not responding to a request within 30 seconds (which could be increased to 60 seconds). the doucmentation mentions that you could contact support to increase the value above 60 seconds... http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html#request-custom-request-timeout

**Comment by ILLUMINICE** [comment] 2017-07-20 08:52
Hi Michael,

As I now understand this, when you're using CloudFront all traffic to the web-servers pass through the CDN first, whether it's a download or upload. Right?

Thank you for helping to clarify the cause of this. So basically when you initiate a plugin update in WordPress, CloudFront is then waiting for a response from WP, which doesn't come fast enough apparently. I can see how the large plugin updates may cause this.

Also, just to clarify, do you think I will encounter any similar issues when uploading large files through the front-end of our website? We're building an application that allows users to upload media, and I was worried it would encounter this same issue with CloudFront. But from the way you describe this, it sounds like we should be ok.

.....

The link you provided is helpful, but right now we can't modify this timeout because you said it's not yet a paramater in CloudFormation. Perhaps this is something that we should write to the CloudFormation team about?

If you're curious I ended up removing all of my plugins last night, since many had been corrupted by the timeout. I then uploaded them fresh to the EFS using WinSCP, which is how I now manage all files on the EFS. I ended up creating a new work-flow for my plugins where I manually upload them, and don't rely upon the update function in the WP admin. This is actually a lot safer, as I can test plugins first in a dev environment, and then track changes in git. From there I just manually update everything, avoiding this timeout issue completely. With that said, I still want to solve the root cause of this problem, as it can affect other functions.

Lastly, the failing EC2 instances I had last night were completely unrelated to the timeout issue. I think it had to do with the changing of file ownership of wp-config.php. I basically have everything set to apache ownership right now, except things I change regularly like our child theme, and the plugins which I'm updating manually. I wish there was a way to have both WordPress and myself have ownership of the files simultaneously, but it does seem impossible in this setup.

~ Michael

**Comment by michaelwittig** [comment] 2017-07-24 07:35
This sounds like a reasonable workaround until we can change the timeout in CloudFormation.

You can use groups to control access to files for multiple users that are member of the same group

**Comment by ILLUMINICE** [comment] 2017-07-24 07:49
Hi Michael,

Hope you had a good weekend!

Having a parameter to change the timeout in CloudFormation is the real solution here. Is this something we can reach out to the CF team about at AWS, to request they add it? Sometimes writing in can get things done faster.

I just wanted to also confirm these two questions from above...

When using CloudFront, all traffic passes through the CDN first, no matter what kind of traffic?

The timeout shouldn't affect uploads through the front-end of the website?

....

Yes, my workaround is a good one, and I'll likely keep doing things that way. But let's please remember to add this parameter to the template as soon as it becomes available, as it affects WordPress quite badly.

My thanks as always for your support!

~ Michael

**Comment by ILLUMINICE** [comment] 2017-07-24 07:56
I forgot to comment about what you said about group ownership...

I actually tried that approach without success. The issue is that I couldn't find a way to add myself as ec2-user and the apache user to the same group. In fact, I couldn't change the groups that ec2-user belongs to at all (I remember it was a member of the "wheel" group). Even if I could change this, wouldn't those changes be lost when new instances are created?

I do appreciate your thoughts on this, as I know it's off-topic from this thread. The file ownership issue has plagued me since day one.

~ Michael

**Comment by michaelwittig** [comment] 2017-07-25 06:00
> Having a parameter to change the timeout in CloudFormation is the real solution here. Is this something we can reach out to the CF team about at AWS, to request they add it?
If you subscribe to an AWS Support Plan (e.g. developer support) you can open feature requests. I already have a request open, but the more people ask for a feature, the higher it get's prioritized. So, open a request and ask for that feature 👍 

> When using CloudFront, all traffic passes through the CDN first, no matter what kind of traffic?
yes

> The timeout shouldn't affect uploads through the front-end of the website?
that's correct

Regarding the permissions: Just to make sure that I understand you correctly: You want to use the ec2-user to make changes to the files located in /var/www/html ?

**Comment by ILLUMINICE** [comment] 2017-07-25 06:28
Hi Michael,

Thanks for replying to all of my questions! :)

Regarding the feature request, I figured you had likely submitted your own request for this. Thank you for doing that. I would gladly submit my own request to them, but I stopped paying for developer support because I found their responses to be extremely generalized and non-helpful. Right now I'm on the free support plan. Perhaps I can still submit a feature request though. I'll look into this.

Here's what's going on with the file ownership...

I administrate all of our files on the EFS by using WinSCP with an SSH tunnel through the Bastion Host. I'm logging in with the ec2-user (instead of my IAM user) so that the files don't end up with ownership special to me.

The problem is that in order for me to be able to modify any files on the EFS this way they must be owned by the same user I am logged in as (ec2-user). Otherwise I can't delete the files, overwrite them, etc.

On the other hand WordPress also wants ownership for many of it's common functions, like updating plugins, updating WordPress, etc. I tested how this works when WordPress is the owner and group owner simultaneously, or when it is just the owner (and not the group owner), and the other way around. What I discovered is that WordPress must be both the owner and the group owner for everything to work in all situations.

So here's the problem...

It seems that all the files must be owned by "apache" and the group also set to "apache" for WordPress to have complete access. I can only change files if they are owned by ec2-user in WinSCP. I haven't found any way to add ec2-user to the group apache, which would likely solve this problem.

My solution for now was basically to set everything (owner and group) to apache, and then just selectively set certain directories to ec2-user (owner and group) that I need to change regularly (like the child theme).

Optimally I would like to have one set of ownership settings that allow both me and WordPress to modify files. This was no problem in the past when I used to have a dedicated server (non-AWS).

If you have any idea how to achieve this, that would be awesome, because I've tried everything here without success.

~ Michael

**Comment by michaelwittig** [comment] 2017-07-28 06:28
duplicate of #61

**Closed by michaelwittig** 2017-07-28 06:28 UTC

**Comment by ILLUMINICE** [comment] 2017-07-28 23:32
Hi Michael,

You asked me a question about the file ownership issue and I fully responded, but then you just closed this thread without replying... ?

If you know a way to resolve this issue, it would be very helpful to me...

~ Michael

**Comment by sgzijl** [comment] 2018-03-26 14:13
Just to let you know that `OriginReadTimeout: 60` can be set with CloudFormation these days, for example:

```
  CloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Aliases:
        - !Ref DomainName
        - !Sub ${SubDomainName}.${DomainName}
        Comment: !Ref DomainName
        Origins:
        - DomainName: !GetAtt 'LoadBalancer.DNSName'
          Id: elb
          CustomOriginConfig:
            OriginProtocolPolicy: 'https-only'
            OriginReadTimeout: 60

...
```

Probably, this is (partly) what you're looking for?

**Comment by michaelwittig** [comment] 2018-03-27 06:04
https://github.com/widdix/aws-cf-templates/commit/81287a1d60fe6a9f4791a3ca53cd88e4d754a88e

**Comment by ILLUMINICE** [comment] 2018-03-27 19:14
@sgzijl @michaelwittig 

I was surprised to see a response on this very old thread. Thank you for letting me know about the newly added OriginReadTimeout. The last time this was discussed it wasn't yet added to CloudFormation.

From what I've read online this can't be set higher than 60 seconds. Is that true?

I also now have a secondary origin from an S3 bucket, but I don't believe you can set this for that origin type. So I've only added this to my ELB origin.

.....

I've added this to my templates, but don't actually need it anymore for the original reason of this thread. I no longer update any WordPress plugins directly on the instances. Instead I update them in my local environment, then commit to Git, and then deploy the changes via Beanstalk App (https://beanstalkapp.com/). This is a much more controlled and safer method to update WordPress core and plugins. I highly recommend using BeanstalkApp to deploy changes if you happen to be using a Git repo. It works extremely well!

The other precaution I take is to set the DISALLOW_FILE_MODS constant in wp-config.php to true.

define('DISALLOW_FILE_MODS', true);

This completely disables the ability to run plugin and theme updates (and installations) directly within WordPress. We use this to prevent anyone from accidentally running updates directly on the instances, since we only run updates in local environments.

Hopefully this information helps anyone facing similar issues.

Thanks again!

~ Michael
