### ISSUE TITLE
ECS Scaling problem

### ISSUE THREAD

**Issue by bitmatix** [widdix/aws-cf-templates#155] opened 2018-03-12 21:20 UTC
TemplateID: ecs/cluster + ecs/service-cluster-alb.yaml
Region: eu-central-1

I've set up all stacks based on your templates and everything is working fine so far. One problem which I encouter is that the cluster always has 1-2 extra EC2 instance running with 0 tasks.

The configured values for the cluster are:

InstanceType: c4.xlarge
SpotPrice: '0.080'
ContainerMaxCPU: '2048'
ContainerMaxMemory: '3584'
ContainerShortageThreshold: '2'
DesiredCapacity: '2'

and for the services:

DesiredCount: '2'
MinCapacity: '2'
MaxCapacity: '8'

Each container instance should be able to run 2 tasks.

The whole thing should run in two availability zones. Any help with the correct parameters would be appreciated.

**Comment by michaelwittig** [comment] 2018-03-13 10:24
Hi @bitmatix Can you check go the to ECS Management Console UI and check what your ECS instances report for CPU and memory?

**Comment by bitmatix** [comment] 2018-03-13 17:48
Hi @michaelwittig,

did you mean the values in the "ECS Instances"  or in the "Metrics" tab?

**Comment by michaelwittig** [comment] 2018-03-14 11:40
If you click on the "ECS Instances" tab, and then on one of the instances you will see the Registered and Available Resources.
![ecs-instance](https://user-images.githubusercontent.com/950078/37400307-d357227c-2784-11e8-8eaf-2206be90b239.png)

**Comment by bitmatix** [comment] 2018-03-14 12:02
Heres an overview of all instaces:

![bildschirmfoto 2018-03-14 um 12 59 56](https://user-images.githubusercontent.com/283437/37401267-cf6e4584-2787-11e8-9ce5-65d523ad2c67.png)

**Comment by michaelwittig** [comment] 2018-03-19 14:50
I believe the following happens:

Your `ContainerShortageThreshold` is 2 which means that if there is space for 2 or less containers, a new EC2 instance is added to register as an ECS instance. Since you have space for 4 containers in total with 2 ECS instances, you use 2, 2 are left so the scale out happens. Try setting the `ContainerShortageThreshold` value to 1 and you should be fine.

But two things go wrong:

1. The ASG waits for 5 minutes between two scale outs. It turns out, that this is not enough time to have a significant impact on the number of schedule containers in your case. I increase this to 10 minutes in this commit: https://github.com/widdix/aws-cf-templates/commit/2c0c02792609dc951859bd4b87daa167c6d78810
2. The container scheduler was not instructed to spread containers across AZs. That's why all tasks are placed on a single ECS Instance. I improved this in this commit: https://github.com/widdix/aws-cf-templates/commit/b9629af0ee0ca13a40c49e99c55c9fac27b2fcda
3. ECS does not rebalance tasks. https://github.com/aws-samples/ecs-refarch-task-rebalancing

Let me know if this works for you and thanks for reporting with all the details!

**Comment by bitmatix** [comment] 2018-03-20 08:22
Thank you @michaelwittig for looking into it and for the explanation. I've adjusted all the mentioned values (ContainerShortageThreshold + step 1 & 2), deleted the cluster and service stacks and rolled out again. Now there are "only" 3 EC2 instances running. Two of them got tasks running, one not. There must be another problem or am I missing something?

**Comment by michaelwittig** [comment] 2018-03-20 11:02
Q: "in the "ScaleUpPolicy" and "ScaleDownPolicy" shouldn't the "MinAdjustmentStep" be "MinAdjustmentMagnitude"?"
A: "This property replaces the MinAdjustmentStep property." So I believe this shouldn't have an impact because they just renamed the property. But I will update the templates accordingly. https://github.com/widdix/aws-cf-templates/commit/5ee5a6ac2e9c163a2635740f067a949280e4c24c

I just created another cluster using the same configuration as you described in this issue. The end result was a cluster with 2 ecs instances.

My suggestion: The test suite will run now for a few hours. I will release a new version after the testa are green. After that, you can use the normal mechanism to create the stacks. If you continue to se more than 2 instances, you re open the issue? Do you agree?

**Comment by bitmatix** [comment] 2018-03-20 14:02
@michaelwittig sounds great. I've just rolled out some changes and now it looks like there are again 3 EC2 instances and one of them has no task running. I waited a while to see if it gets terminated but that's not happening. The disred count in the ASG stays at 3.  Do you think that I have got to adjust the "ContainerExcessThreshold" value. It is currently set on your default of 10.

**Comment by michaelwittig** [comment] 2018-03-21 06:55
Adjusting the `ContainerExcessThreshold ` will not fix the problem. More like a workaround. So let's see why you still end up with 3 instances...

Could you:

1. go to [CloudWatch alarms](https://console.aws.amazon.com/cloudwatch/home#alarm:alarmFilter=ANY)
2. select the alarm named <ecs-cluster-stack-name>-ContainerInstancesShortageAlarm-<something>
3. select the History tab at the bottom half of the screen
4. make a screenshot of the table
5. drag&drop the screenshot here
6. If you find an entry like "Alarm updated from OK to ALARM" please expand the entry and copy&paste the JSON as well

With this information, we can find out why the cluster scales up.

**Comment by bitmatix** [comment] 2018-03-21 07:03
<img width="1093" alt="bildschirmfoto 2018-03-21 um 07 58 39" src="https://user-images.githubusercontent.com/283437/37697646-4aed9ba0-2cde-11e8-8159-00fb2c5a5e7b.png">

```
{
  "version": "1.0",
  "oldState": {
    "stateValue": "OK",
    "stateReason": "Threshold Crossed: 1 datapoint [2.0 (20/03/18 21:25:00)] was not less than or equal to the threshold (1.0).",
    "stateReasonData": {
      "version": "1.0",
      "queryDate": "2018-03-20T21:26:14.877+0000",
      "startDate": "2018-03-20T21:25:00.000+0000",
      "statistic": "Minimum",
      "period": 60,
      "recentDatapoints": [
        2
      ],
      "threshold": 1
    }
  },
  "newState": {
    "stateValue": "ALARM",
    "stateReason": "Threshold Crossed: 1 datapoint [0.0 (20/03/18 22:17:00)] was less than or equal to the threshold (1.0).",
    "stateReasonData": {
      "version": "1.0",
      "queryDate": "2018-03-20T22:18:21.077+0000",
      "startDate": "2018-03-20T22:17:00.000+0000",
      "statistic": "Minimum",
      "period": 60,
      "recentDatapoints": [
        0
      ],
      "threshold": 1
    }
  }
}
```

**Comment by bitmatix** [comment] 2018-03-23 13:58
@michaelwittig can it be a problem with something I've got in the "UserData" section of my cluster template?

**Comment by michaelwittig** [comment] 2018-03-23 14:16
What we see from the alarm history, that the scale up (23:18) does not happen during cluster creation (22:26).I believe that the problem is not related to the creation of the cluster.

Next question: What happened to the cluster at around 23:18 on Match 20th. Do you still have the ECS service available where we could check the events?

Regarding your User Data: Yes it could :) If you modify the template I can no longer reproduce the issue. Could you explain (or show) what you added to the user data?

**Comment by bitmatix** [comment] 2018-03-23 14:32
@michaelwittig I'm afraid the ECS from March 20th is not available any more, but the current ECS has got the same problem. Still 3 instances running, 1 instance without task.

The "UserData" section of the cluster looks like this:

```
      UserData: !Base64
        Fn::Join:
          - ''
          - - "#!/bin/bash\n"
            - echo ECS_CLUSTER=
            - !Ref Cluster
            - " >> /etc/ecs/ecs.config\n"
            - "yum install -y aws-cfn-bootstrap\n"
            - /opt/aws/bin/cfn-init
            - '         --stack '
            - !Ref 'AWS::StackName'
            - ' '
            - '         --resource LaunchConfiguration '
            - '         --region '
            - !Ref 'AWS::Region'
            - "\n"
            - NEWRELIC_LICENSE_KEY=
            - !Ref NewRelicLicenseKey
            - "\n"
            - "yum update\n"
            - "echo \"license_key: $NEWRELIC_LICENSE_KEY\" | sudo tee -a /etc/newrelic-infra.yml\n"
            - "curl -o /etc/yum.repos.d/newrelic-infra.repo https://download.newrelic.com/infrastructure_agent/linux/yum/el/6/x86_64/newrelic-infra.repo\n"
            - "yum -q makecache -y --disablerepo='*' --enablerepo='newrelic-infra'\n"
            - "yum install newrelic-infra -y\n"
            - "PATH=$PATH:/usr/local/bin\n"
            - "yum -y install nfs-utils\n"
            - "EC2_AVAIL_ZONE=`curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone`\n"
            - EC2_REGION=
            - !Ref 'AWS::Region'
            - "\n"
            - "mkdir /mnt/efs\n"
            - EFS_FILE_SYSTEM_ID=
            - !Ref FileSystemID
            - "\n"
            - "DIR_SRC=$EC2_AVAIL_ZONE.$EFS_FILE_SYSTEM_ID.efs.$EC2_REGION.amazonaws.com\n"
            - "DIR_TGT=/mnt/efs\n"
            - "touch /home/ec2-user/echo.res\n"
            - "echo $EFS_FILE_SYSTEM_ID >> /home/ec2-user/echo.res\n"
            - "echo $EC2_AVAIL_ZONE >> /home/ec2-user/echo.res\n"
            - "echo $EC2_REGION >> /home/ec2-user/echo.res\n"
            - "echo $DIR_SRC >> /home/ec2-user/echo.res\n"
            - "echo $DIR_TGT >> /home/ec2-user/echo.res\n"
            - "mount -t nfs4 $DIR_SRC:/ $DIR_TGT >> /home/ec2-user/echo.res\n"
            - "cp -p /etc/fstab /etc/fstab.back-$(date +%F)\n"
            - "echo -e \"$DIR_SRC:/ \t\t $DIR_TGT \t\t nfs \t\t defaults \t\t 0 \t\
              \t 0\" | tee -a /etc/fstab\n"
            - "mkdir -p /mnt/efs/data/uploads /mnt/efs/data/cache /mnt/efs/data/cache/nginxfastcgi\n"
            - "chown -R 1000:1000 /mnt/efs/data/uploads /mnt/efs/data/cache /mnt/efs/data/cache/nginxfastcgi\n"
            - "stop ecs\n"
            - "service docker restart\n"
            - "start ecs\n"
            - '/opt/aws/bin/cfn-signal -e $? '
            - '         --stack '
            - !Ref 'AWS::StackName'
            - '         --resource AutoScalingGroup '
            - '         --region '
            - !Ref 'AWS::Region'
            - "\n"
```

**Comment by bitmatix** [comment] 2018-03-24 23:59
@michaelwittig I've updated the "UserData" section and put the EFS part into the LaunchConfiguration. So the "UserData" now looks like this:

```
     UserData:
        'Fn::Base64': !Sub |
          #!/bin/bash -ex
          trap '/opt/aws/bin/cfn-signal -e 1 --stack ${AWS::StackName} --resource AutoScalingGroup --region ${AWS::Region}' ERR
          echo "ECS_CLUSTER=${Cluster}" >> /etc/ecs/ecs.config
          yum install -y aws-cfn-bootstrap
          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource LaunchConfiguration --region ${AWS::Region}
          /opt/aws/bin/cfn-signal -e 0 --stack ${AWS::StackName} --resource AutoScalingGroup --region ${AWS::Region}
```

and the "mount" part in "LaunchConfiguration" looks like this:

```
        mount:
          packages:
            yum:
              nfs-utils: []
          commands:
            a_create_dir:
              command: !Sub "mkdir -p /mnt/efs"
            b_mount:
              command: !Sub "mount -t nfs4 -o nfsvers=4.1 ${FileSystemID}.efs.${AWS::Region}.amazonaws.com:/ /mnt/efs"
            c_fstab:
              command: !Sub "echo ${FileSystemID}.efs.${AWS::Region}.amazonaws.com:/ /mnt/efs nfs4 nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 0 0\" >> /etc/fstab"
            d_create_additional_dirs:
              command: !Sub "mkdir -p /mnt/efs/data/uploads /mnt/efs/data/cache /mnt/efs/data/cache/nginxfastcgi"
            e_permissions:
              command: !Sub "chown -R 1000:1000 /mnt/efs"
            f_restart_docker_and_ecs:
              command: !Sub "stop ecs && service docker restart && start ecs"
```

but there's still the problem with the third EC2 instance, which has no task running.

**Comment by bitmatix** [comment] 2018-03-25 18:35
@michaelwittig I've modified the settings for the cluster template and with the following ones I've got 2  tasks running on 2 EC2 instances:

ContainerShortageThreshold: '1'
ContainerExcessThreshold: '3'

**Comment by michaelwittig** [comment] 2018-03-26 09:38
I'm happy to hear that the cluster is working now. The settings depend on your specific workload. I will close this case for now.

**Closed by michaelwittig** 2018-03-26 09:38 UTC
Labels: Bug
