### ISSUE TITLE
Jenkins 2.89.2 deprecated protocols: JNLP-connect,JNLP2-connect for agents

### ISSUE THREAD

**Issue by sandrokeil** [widdix/aws-cf-templates#144] opened 2018-01-08 06:42 UTC
TemplateID: `jenkins/jenkins2-ha-agents`
Region: all

With the newest template Version and Jenkins 2.89.2 I've got the following warning:

>This Jenkins instance uses deprecated protocols: JNLP-connect,JNLP2-connect. It may impact stability of the instance. If newer protocol versions are supported by all system components (agents, CLI and other clients), it is highly recommended to disable the deprecated protocols.

As far as I can see, the agents uses [JNLP](https://github.com/widdix/aws-cf-templates/blob/master/jenkins/jenkins2-ha-agents.yaml#L1558). Any plans/ideas how to fix this?

**Comment by michaelwittig** [comment] 2018-01-08 13:35
Hi @sandrokeil 

under `/configureSecurity/`go to the ** Agents** section, click on the **Agent protocols...** button, make sure that only version 4 is selected. Save the changes. Does this resolve the warning?

If yes, I have to figure out how to change the xml to make this the default configuration...

**Comment by sandrokeil** [comment] 2018-01-09 07:05
It works like a charm. Thank you very much @michaelwittig

**Comment by michaelwittig** [comment] 2018-01-09 07:39
The issue is only relevant for existing Jenkins installations. New installations will have the configuration by default. So I close this issue without any changes.

**Closed by michaelwittig** 2018-01-09 07:39 UTC
Labels: Bug

**Comment by karunakaretg** [comment] 2018-03-23 05:17
Its working @michaelwittig
