### ISSUE TITLE
Unable to Change or Delete Files on EFS in WordPress Template

### ISSUE THREAD

**Issue by ILLUMINICE** [widdix/aws-cf-templates#83] opened 2017-06-21 16:33 UTC
Hi Andreas,

I'm posting this in a separate issue since you said it was no longer related to my original post.

Now that you have helped me to gain direct access to the EFS, I have found that I am unable to change or delete any files there (which is obviously the entire point). I'm using WinSCP with an SSH tunnel direct to the EFS on one of the WordPress instances. I'm also using the sFTP protocol because the SCP protocol does not support deleting items.

Whenever I try to either delete a file or overwrite a file I receive the following error message:

**Permission denied.
Error code: 3
Error message from server: Permission denied**

I noticed that all the files are owned by Apache, and perhaps this is the source of the problem? Assuming I am right, do you know how to work around this?

I hope you can help, as without being able to change files on the EFS my project cannot proceed.

All my best,

~ Michael

**Comment by michaelwittig** [comment] 2017-06-22 06:15
which linux user are you using to login?

**Comment by ILLUMINICE** [comment] 2017-06-22 06:58
Hi Michael,

It's very late here, but I saw your message and wanted to respond without delay. The different time-zones have made communications slow to say the least.

Thank you for getting back to me, and I apologize for confusing you with Andreas earlier. Andreas had been helping me up until now.

To answer your question I had been logging in using my IAM credentials (through the SSH tunnel). I just tried using the ec2-user credentials and had the same result. Whether I try to delete a file, or overwrite one, I receive the same error.

I'm open to any suggestions you have. It's critical that I can alter files so we can customize our site. I hope you can help!

~ Michael

**Comment by ILLUMINICE** [comment] 2017-06-22 07:04
Here's a screenshot of the error I'm seeing in WinSCP...

![screenshot](https://user-images.githubusercontent.com/11562655/27421225-5ce52dd6-56de-11e7-9a5e-f6fb14e8aa4b.jpg)

**Comment by michaelwittig** [comment] 2017-06-22 13:14
the file is owned by the user apache and has the following access rights:
apache user: read and write
??? group: read (I can't see the group of the file on your WinSCP client)
others: read

As longs as you are not logged in as apache user you can not edit the files unless you don't change the file permissions. You can learn more here https://www.linux.com/learn/understanding-linux-file-permissions

The issue is related to file permissions and not the CloudFormation template. I will close this.

**Closed by michaelwittig** 2017-06-22 13:14 UTC

**Comment by ILLUMINICE** [comment] 2017-06-22 16:52
These files were created by your WordPress Aurora CloudFormation template, so why do you say it's unrelated?

Without being able to change/modify the files, the template is completely useless! I'm willing to make the necessary changes to correct this, but you've left me with no support again.

I'm extremely frustrated that every time I try to ask something I am either ignored, or told it's unrelated to the templates. I donated money to you and Andreas for your efforts in making the Aurora template, and with the hopes you would at least answer some basic setup questions. As of this moment I am left with no help and a template I cannot start using.

~ Michael

**Comment by ILLUMINICE** [comment] 2017-06-23 02:10
Hi Michael,

I just sent you a direct email with a proposed solution to this issue and many of my other questions. If you would take just a moment to look at my email I would greatly appreciate it. If you saw my earlier message, I was simply frustrated, and hope you understand.

All my best,

~ Michael
